## other configuration excluded from example...
exclude_patterns:
- "UI/*"
- "PlaceMeDemo/droidAR/*"
- "PlaceMe/PlaceMeDemo/app/src/main/res/*"
- "PlaceMe/PlaceMeDemo/app/src/main/java/placeme/ru/placemedemo/core/Controller.java"
